/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RecipesRouteImport } from './routes/recipes/route'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIndexImport } from './routes/recipes/index'
import { Route as RecipesAddIndexImport } from './routes/recipes/add/index'

// Create/Update Routes

const RecipesRouteRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIndexRoute = RecipesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRouteRoute,
} as any)

const RecipesAddIndexRoute = RecipesAddIndexImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => RecipesRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRoute
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexImport
      parentRoute: typeof RecipesRouteImport
    }
    '/recipes/add/': {
      id: '/recipes/add/'
      path: '/add'
      fullPath: '/recipes/add'
      preLoaderRoute: typeof RecipesAddIndexImport
      parentRoute: typeof RecipesRouteImport
    }
  }
}

// Create and export the route tree

interface RecipesRouteRouteChildren {
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesAddIndexRoute: typeof RecipesAddIndexRoute
}

const RecipesRouteRouteChildren: RecipesRouteRouteChildren = {
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesAddIndexRoute: RecipesAddIndexRoute,
}

const RecipesRouteRouteWithChildren = RecipesRouteRoute._addFileChildren(
  RecipesRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRouteRouteWithChildren
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/add': typeof RecipesAddIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/recipes/add': typeof RecipesAddIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/recipes': typeof RecipesRouteRouteWithChildren
  '/recipes/': typeof RecipesIndexRoute
  '/recipes/add/': typeof RecipesAddIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/recipes' | '/recipes/' | '/recipes/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes' | '/recipes/add'
  id: '__root__' | '/' | '/recipes' | '/recipes/' | '/recipes/add/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesRouteRoute: typeof RecipesRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesRouteRoute: RecipesRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/recipes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/recipes": {
      "filePath": "recipes/route.tsx",
      "children": [
        "/recipes/",
        "/recipes/add/"
      ]
    },
    "/recipes/": {
      "filePath": "recipes/index.tsx",
      "parent": "/recipes"
    },
    "/recipes/add/": {
      "filePath": "recipes/add/index.tsx",
      "parent": "/recipes"
    }
  }
}
ROUTE_MANIFEST_END */
